###**AULA 2 - Biblioteca NumPy**

In [1]:
#importando a biblioteca numpy
import numpy as np

In [2]:
# Criar lista
minha_lista = [1,2,3,4,5]
minha_lista

[1, 2, 3, 4, 5]

###**Construindo arrays**

**Array unidimensional**

In [3]:
#array unidimensional 1-D:
array_unidimensional = np.array([0, 1, 2, 3,4,5])
array_unidimensional

array([0, 1, 2, 3, 4, 5])

In [4]:
#dimensão do array
array_unidimensional.ndim

1

In [5]:
#vefificando a dimensão do array: shape
#O atributo shape retorna uma tupla que consiste nas dimensões da Array, mostrando quantas linha e colunas temos
print(array_unidimensional.shape)

(6,)


In [6]:
len(array_unidimensional)

6

In [7]:
#tipo do array
print('Tipo: ',type(array_unidimensional))

#tamanho do array
print("Size:", array_unidimensional.size)

Tipo:  <class 'numpy.ndarray'>
Size: 6


In [8]:
#especificando o tipo de dado
array_float = np.array([1, 2, 3], dtype=float)
print(array_float)
print(array_float.dtype)

[1. 2. 3.]
float64


In [9]:
#array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
array_esparso = np.arange(10, 50, 5)
array_esparso

array([10, 15, 20, 25, 30, 35, 40, 45])

**Array dimensional**

In [10]:
array_2d = np.array([[0, 1, 2], [3, 4, 5]])    # 2 linhas x 3 colunas
print(array_2d)


[[0 1 2]
 [3 4 5]]


In [11]:
print('Dimensão: ', array_2d.ndim)
print('Linha x coluna: ',array_2d.shape)

Dimensão:  2
Linha x coluna:  (2, 3)


In [12]:
#mostra o tipo de dado do array
array_2d.dtype

dtype('int32')

In [13]:
array_2d.size

6

In [14]:
# Len mostra quantas linhas tem
len(array_2d)

2

In [15]:
#Podemos também imprimir os elementos individuais. Assim como um Array Python, os Arrays NumPy são indexados começando do 0.
print(array_2d[0]) 
print(array_2d[1]) 

print('Valor que etá no indice 2 da linha 1 é', array_2d[1][2])

print('Todos os elementos da linha a partir da coluna1:', array_2d[0][:3])

[0 1 2]
[3 4 5]
Valor que etá no indice 2 da linha 1 é 5
Todos os elementos da linha a partir da coluna1: [0 1 2]


In [16]:
#Também podemos modificar os elementos de um Array. Por exemplo, suponha que escrevamos o seguinte comando:
#alterar o elemento de índice 1 do array da linha 0
array_2d[0][1] = 2
print(array_2d) 

[[0 2 2]
 [3 4 5]]


**Array tridimensional**

In [17]:
array_3d = np.array([[[ 0,  1,  2,  3],
[ 4,  5,  6,  7],
[ 8,  9, 10, 11]],
[[12, 13, 14, 15],
[16, 17, 18, 19],
[20, 21, 22, 23]]])

array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
print(array_3d.ndim)
print(array_3d.shape)
print(len(array_3d) ) 

3
(2, 3, 4)
2


###**Matrizes comuns**

In [19]:
#array de zeros
array_zeros = np.zeros((5)) 
print(array_zeros)

[0. 0. 0. 0. 0.]


In [20]:
#array de zeros
array_zeros2 = np.zeros((2, 5)) 
print(array_zeros2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#array de uns
array_um = np.ones((3, 3))  # lembrete: (3, 3) é uma tupla
array_um

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#matriz diagonal de uns
c = np.eye(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
#matriz diagonal
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

###**Array de valores aleatórios**

In [24]:
?np.random

In [25]:
a = np.random.rand(4, 2)       # uniforme em [0, 1]
a 

array([[0.12072192, 0.95119087],
       [0.22216587, 0.83531428],
       [0.40420573, 0.60776334],
       [0.51249782, 0.99046327]])

In [26]:
my_random_array = np.random.random((5)) 
print(my_random_array)

[0.42796673 0.3231568  0.14772091 0.80189087 0.57564622]


In [27]:
#Números aleatórios entre 0 e 10
array_aleatorio = np.floor(10*np.random.random((3,4))) 
print(array_aleatorio)

[[6. 7. 1. 2.]
 [0. 0. 2. 7.]
 [5. 0. 8. 3.]]


In [28]:
#Números aleatórios entre 0 e 100
array_aleatorio = np.floor(100*np.random.random((3,4)))
print(array_aleatorio)

[[75. 26. 35. 53.]
 [20. 53.  9. 71.]
 [81. 85. 71. 31.]]


##**Cálculos matemáticos com arrays**

In [29]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])

soma = a + b # Soma
subtracao = a - b # Subtração
multiplicacao = a * b # Multiplicação
divisao = a / b # Divisão

print('A = \n', + a)
print('\n')

print('B = \n', + b)
print('\n')

print('Soma = \n', + soma)
print('\n')
print('Subtração = \n', + subtracao)
print('\n')
print('Multiplicação = \n', + multiplicacao)
print('\n')
print('Divisão = \n', + divisao)

A = 
 [[1. 2.]
 [3. 4.]]


B = 
 [[5. 6.]
 [7. 8.]]


Soma = 
 [[ 6.  8.]
 [10. 12.]]


Subtração = 
 [[-4. -4.]
 [-4. -4.]]


Multiplicação = 
 [[ 5. 12.]
 [21. 32.]]


Divisão = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [30]:
'''Como você pode ver, o operador de multiplicação executa a multiplicação por elementos em vez da multiplicação de arrays. 
Para executar a multiplicação de arrays, você pode fazer o seguinte:'''

matrix_product = a.dot(b)  
print('Produto matriz = \n', + matrix_product)

Produto matriz = 
 [[19. 22.]
 [43. 50.]]


In [31]:
x = a.transpose
x

<function ndarray.transpose>

###**Funções de agregações**

In [32]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print('Mínimo: ', a.min())
print('Máximo: ', a.max())
print('Soma: ', a.sum())
print('Média: ', a.mean())
print('Desvio Padrão: ', a.std())

Mínimo:  1.0
Máximo:  4.0
Soma:  10.0
Média:  2.5
Desvio Padrão:  1.118033988749895


###**Função where**

Referência: https://www.educba.com/numpy-where/

In [33]:
a1 = np.array([[10, 20, 30], [40, 50, 60]])
print ('Array a1: \n', a1)

#definindo a condição a1>30
ans = np.where(a1>30)

print ('\nMostrando todos os elementos do Array a1 - maiores que 30: \n', a1[ans])


Array a1: 
 [[10 20 30]
 [40 50 60]]

Mostrando todos os elementos do Array a1 - maiores que 30: 
 [40 50 60]


###**Função numpy.linspace()**

In [34]:
#numpy.linspace() é uma função usada para criar sequencia numérica com um intervalo específico

#inicio 3, fim 7 - por padrão são gerados 50 números
np.linspace(3.0, 7.0)

array([3.        , 3.08163265, 3.16326531, 3.24489796, 3.32653061,
       3.40816327, 3.48979592, 3.57142857, 3.65306122, 3.73469388,
       3.81632653, 3.89795918, 3.97959184, 4.06122449, 4.14285714,
       4.2244898 , 4.30612245, 4.3877551 , 4.46938776, 4.55102041,
       4.63265306, 4.71428571, 4.79591837, 4.87755102, 4.95918367,
       5.04081633, 5.12244898, 5.20408163, 5.28571429, 5.36734694,
       5.44897959, 5.53061224, 5.6122449 , 5.69387755, 5.7755102 ,
       5.85714286, 5.93877551, 6.02040816, 6.10204082, 6.18367347,
       6.26530612, 6.34693878, 6.42857143, 6.51020408, 6.59183673,
       6.67346939, 6.75510204, 6.83673469, 6.91836735, 7.        ])

In [35]:
#inicio 3, fim 7 - e parada: 10 valores
np.linspace(3.0, 7.0, num = 10)

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

###**Ajuda interativa**

In [36]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [37]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a 